// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzQlg9u7xPnu7shPiiiWDmRSJfxCIuOAE',
    appId: '1:983577813931:web:3a67e087bef016826068ee',
    messagingSenderId: '983577813931',
    projectId: 'my-akastra',
    authDomain: 'my-akastra.firebaseapp.com',
    storageBucket: 'my-akastra.firebasestorage.app',
    measurementId: 'G-KYXRPBZEFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FBt737Xr163ElsjnofcHkSVXqYVK618',
    appId: '1:983577813931:android:3ddc40de72673f8b6068ee',
    messagingSenderId: '983577813931',
    projectId: 'my-akastra',
    storageBucket: 'my-akastra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDwh0DJPjQSl3UdMXdLxcyGefj_ds86zw',
    appId: '1:983577813931:ios:f01dc88a92dfe0236068ee',
    messagingSenderId: '983577813931',
    projectId: 'my-akastra',
    storageBucket: 'my-akastra.firebasestorage.app',
    iosBundleId: 'com.example.myAkastra.myAkastraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDwh0DJPjQSl3UdMXdLxcyGefj_ds86zw',
    appId: '1:983577813931:ios:f01dc88a92dfe0236068ee',
    messagingSenderId: '983577813931',
    projectId: 'my-akastra',
    storageBucket: 'my-akastra.firebasestorage.app',
    iosBundleId: 'com.example.myAkastra.myAkastraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzQlg9u7xPnu7shPiiiWDmRSJfxCIuOAE',
    appId: '1:983577813931:web:2c3d8fbfcf90407d6068ee',
    messagingSenderId: '983577813931',
    projectId: 'my-akastra',
    authDomain: 'my-akastra.firebaseapp.com',
    storageBucket: 'my-akastra.firebasestorage.app',
    measurementId: 'G-T36YMC5MCV',
  );
}
